# GrimAC main configuration
# Source code: https://github.com/Elic0de/H1
# Copyright 2022 Elic0de and contributors, Licensed under GPLv3.
# Modified binaries, or plugins with copied grim code, must be private,
# or with full source code available to buyers at no additional cost.

config-version: 3

海鮮丼:
  mana: 5
  point: 1

恵方巻:
  mana: 5
  point: 1